### ISSUE TITLE
Pass the tests for 1.7

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow-pipelines#28]
How to build the code: 
1) Ensure you are running on node v12, I used nvm
2) `cd /frontend`
3) `npm test` 
    a dialog prompt will come up just press 'a' to do all of them

The current results:
![image](https://user-images.githubusercontent.com/14837042/183499756-86dc90c7-4b49-493b-8fe4-bd207e31f951.png)

I can't seem to get a good list of all failed tests so here is a badly composed version
Other:
- [x] Missing all the pages now

Components tabs:
- [x] InputOutputTab
- [x] MetricsTab 7  missed

Viewer:
- [x] Tensorboard

Components:
- [x]  npm test ExperimentList
- [x] Metric
- [x] SideNav
- [x] Trigger

Pages:
- [x] ExperimentDetails 4 failed
- [x] PipelineDetails 8 failed
- [x] PipelineDetailsV1
- [x] RecurringRunList

- [x] Workflow Parser

Update on amount of tests to fix as of 12/08/22:
![image](https://user-images.githubusercontent.com/14837042/184366903-c617ccfd-49a9-4a02-935a-51b20104ef0d.png)

**Comment by wg102** [comment]
Missing content discovered: 
- [x] ArtifactPreview
- [x] ExecutionTitle ln 32
- [x] RunListRouter ln 68
-  ~~Metrics ln 72~~
- [x] Recurring Work is broken

**Comment by wg102** [comment]
Many of the tests were broken because of out of date snapshots. 
Once those were corrected, most had issues because the code in the test expect 'Hello' but the real code is 'common:hello' I will attempt to fix those

**Comment by wg102** [comment]
Fixed RecurringRunList
There were two issues, 
1. `t` was not correctly called in the non-render functions, it needed to be `this.props.t`
2. The tests work, but it finds the translation key and not message. Adjusted the test.

**Comment by wg102** [comment]
Fixed Tensorboard:
The issue was that upstream removed {this.state.tensorflowVersion} and our code still had it. 
Also had to update the snapshots

**Comment by wg102** [comment]
MetricsTab: There are 7 tests failing. 
But also an error when trying to execute `npm test MetricsTab` and it might hide more issues

**Comment by wg102** [comment]
PipelineDetailsV1: T
The evaluations gave things like `t('common:home)' which was because of missing `{ }` around the t function
Also added the T Function to the file.

**Comment by wg102** [comment]
I am actually doubting the way I fixed the tests...
```
jest.mock('react-i18next', () => ({
    // this mock makes sure any components using the translate hook can use it without a warning being shown
    withTranslation: () => (Component: { defaultProps: any }) => {
      Component.defaultProps = { ...Component.defaultProps, t: (key: string) => key };
      return Component;
    },
    useTranslation: () => {
      return {
        t: (key: string) => key,
        i18n: {
          changeLanguage: () => new Promise(() => {}),
        },
      };
    },
  }));
```
This seems to be the way we did it in some of our code, but it doesn't seem to be usable on all methods either.

**Comment by wg102** [comment]
MetricsTab is very tricky, There are currently 7 tests failing, and It might be for a different reason than the test needing adjustment.
```
 Something went wrong.
          </h2>
          <details
            style="white-space: pre-wrap;"
          >
            TypeError: Cannot read property 'getDisplayName' of undefined
            <br />
            
        in MetricsVisualizations (at MetricsTab.tsx:119)
        in div (at MetricsTab.tsx:95)
        in div (at MetricsTab.tsx:94)
        in ErrorBoundary (at MetricsTab.tsx:93)
        in MetricsTab (at MetricsTab.test.tsx:383)
        in QueryClientProvider (at TestWrapper.tsx:28)
        in Router (created by BrowserRouter)
        in BrowserRouter (at TestWrapper.tsx:27)
        in CommonTestWrapper (at MetricsTab.test.tsx:382)
          </details>
        </div>

```

**Comment by wg102** [comment]
There are as of Aug 22nd, 13 tests still failing. Most of them within 2 categories:
1. Invalid Web Hook: This might be due to having i18n calling the hook in an invalid place, aka return statement. 
2. Property 'prototype' does not exist on type 'ViewerProperties'. Which might have something to do with es5. It works fine on upstream 1.7 branch, with the very same code. Maybe we broke something. Might be a link missing or a converstion

**Comment by wg102** [comment]
Fixed the issues with MetricsTab.
![image](https://user-images.githubusercontent.com/14837042/185957629-fc5302ab-95cd-4f9e-88a0-22ec4c3e7b47.png)

**Comment by mathis-marcotte** [comment]
Fixed issue with tests in PipelineDetailsTest.test. Added the same translation configs that were in PipelineDetails.test and changed the expected message to use the translation keys instead of the full message.

![Capture](https://user-images.githubusercontent.com/84033116/186001170-e22e7791-9a08-405d-b3db-7202a4ecd5a6.PNG)

**Comment by wg102** [comment]
WorkflowParser fixed, it was missing the variable t in the function, and therefore considering the two arguments it got as not the right ones.

**Comment by wg102** [comment]
The last failing test seems to be due to the `T function` staying when it should clear:
```
it("doesn't keep error message for request from previous namespace", async () => {
      //The issue is that it keeps the t function...
      listExperimentsSpy.mockImplementation(() => Promise.reject('namespace cannot be empty'));
      const { rerender } = render(
        <MemoryRouter>
          <NamespaceContext.Provider value={undefined}>
            <EnhancedExperimentList {...generateProps()} />
          </NamespaceContext.Provider>
        </MemoryRouter>,
      );

      listExperimentsSpy.mockImplementation(mockListNExpperiments());
      rerender(
        <MemoryRouter>
          <NamespaceContext.Provider value={'test-ns'}>
            <EnhancedExperimentList {...generateProps()} />
          </NamespaceContext.Provider>
        </MemoryRouter>,
      );
      await act(TestUtils.flushPromises);
      expect(updateBannerSpy).toHaveBeenLastCalledWith(
        {t}, // Empty object means banner has no error message
      );
    });
```
![image](https://user-images.githubusercontent.com/14837042/186443543-4d52dd4c-a463-48c2-8117-3acfff0cbe89.png)

It seems like it doubles up the `t function`, which should be there only one, maybe even 0 times...

**Comment by wg102** [comment]
Closed in the PR above.
